package com.icei.mapper;

import org.apache.ibatis.annotations.Param;

import com.icei.domain.AssessImg;

public interface AssessImgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assess_img
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int deleteByPrimaryKey(Integer imgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assess_img
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insert(AssessImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assess_img
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insertSelective(AssessImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assess_img
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    AssessImg selectByPrimaryKey(Integer imgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assess_img
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int updateByPrimaryKeySelective(AssessImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assess_img
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int updateByPrimaryKey(AssessImg record);
    /**
     * 删除评论图片
     * @param assessId 评论id
     * @return
     */
    int delAssessImg(@Param("assessId")Integer assessId);
}