package com.icei.mapper;

import java.util.List;

import com.icei.domain.AssessTag;

public interface AssessTagMapper {
	
	/**
	 * 得到全部评论类型
	 * @return
	 */
	List<AssessTag> getAll();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assess_tag
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int deleteByPrimaryKey(Integer assessTagid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assess_tag
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insert(AssessTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assess_tag
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insertSelective(AssessTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assess_tag
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    AssessTag selectByPrimaryKey(Integer assessTagid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assess_tag
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int updateByPrimaryKeySelective(AssessTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assess_tag
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int updateByPrimaryKey(AssessTag record);
}