package com.icei.mapper;

import com.icei.domain.AssessLikeRelation;

public interface AssessLikeRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assess_like_relation
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insert(AssessLikeRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assess_like_relation
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insertSelective(AssessLikeRelation record);
}