package com.icei.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.icei.domain.AssessReport;
import com.icei.domain.BrandAudit;

public interface AssessReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assess_report
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int deleteByPrimaryKey(Integer auditId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assess_report
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insert(AssessReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assess_report
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insertSelective(AssessReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assess_report
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    AssessReport selectByPrimaryKey(Integer auditId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assess_report
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int updateByPrimaryKeySelective(AssessReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table assess_report
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int updateByPrimaryKey(AssessReport record);
    //分页查询
    List<AssessReport> getAssessReportPage(Map<String, Object> map);
    //查询总条数
    int getCount(@Param("id")Integer id,@Param("val")String val);
}