package com.icei.mapper;

import com.icei.domain.AuditStatus;

public interface AuditStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audit_status
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int deleteByPrimaryKey(Integer statusId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audit_status
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insert(AuditStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audit_status
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insertSelective(AuditStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audit_status
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    AuditStatus selectByPrimaryKey(Integer statusId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audit_status
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int updateByPrimaryKeySelective(AuditStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audit_status
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int updateByPrimaryKey(AuditStatus record);
}