package com.icei.mapper;

import com.icei.domain.BillOrder;

public interface BillOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_order
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insert(BillOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill_order
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insertSelective(BillOrder record);
}