package com.icei.mapper;

import com.icei.domain.BrandPrincipal;

public interface BrandPrincipalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_principal
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int deleteByPrimaryKey(Integer auditId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_principal
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insert(BrandPrincipal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_principal
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insertSelective(BrandPrincipal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_principal
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    BrandPrincipal selectByPrimaryKey(Integer auditId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_principal
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int updateByPrimaryKeySelective(BrandPrincipal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_principal
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int updateByPrimaryKey(BrandPrincipal record);
}