package com.icei.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.icei.domain.BrandAdminSublevel;

public interface BrandAdminSublevelMapper {
	
	int getAllCount(@Param("id")int id);
	
	List<BrandAdminSublevel> getAll(@Param("id")int id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_admin_sublevel
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int deleteByPrimaryKey(Integer sublevelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_admin_sublevel
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insert(BrandAdminSublevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_admin_sublevel
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insertSelective(BrandAdminSublevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_admin_sublevel
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    BrandAdminSublevel selectByPrimaryKey(Integer sublevelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_admin_sublevel
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int updateByPrimaryKeySelective(BrandAdminSublevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_admin_sublevel
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int updateByPrimaryKey(BrandAdminSublevel record);
}