package com.icei.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.icei.domain.Brand;
@Mapper
public interface BrandMapper {
	/**
	 * 个人中心关注店铺
	 * @param userId
	 * @return
	 */
	List<Brand> getUserLikeBrand(@Param("userId")int userId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int deleteByPrimaryKey(Integer brandId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insert(Brand record);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insertSelective(Brand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    Brand selectByPrimaryKey(Integer brandId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int updateByPrimaryKeySelective(Brand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int updateByPrimaryKey(Brand record);

    /**
     * 全部店铺
     * @return
     */
    List<Brand>	getBrandAll();
    /**
     * 分页店铺信息
     * @return	List<Brand>
     */
    List<Brand>	selectAllMessage(Map<String,Object> map);
    
    /**
     * 查询总条数
     * @return 	int
     */
    int selectByidCount(@Param("id")int id,@Param("nametype")String nametype);
    
    /**
     * 根据商品的状态修改
     * @param num	状态
     * @return	int
     */
    int updateByStatus(@Param("id")int id,@Param("num")int num);
}