package com.icei.mapper;

import com.icei.domain.BrandPowerRoleAuth;

public interface BrandPowerRoleAuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_power_role_auth
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insert(BrandPowerRoleAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_power_role_auth
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insertSelective(BrandPowerRoleAuth record);
}