package com.icei.mapper;

import com.icei.domain.BrandPowerAuthority;

public interface BrandPowerAuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_power_authority
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int deleteByPrimaryKey(Integer authorityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_power_authority
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insert(BrandPowerAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_power_authority
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insertSelective(BrandPowerAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_power_authority
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    BrandPowerAuthority selectByPrimaryKey(Integer authorityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_power_authority
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int updateByPrimaryKeySelective(BrandPowerAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_power_authority
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int updateByPrimaryKey(BrandPowerAuthority record);
}