package com.icei.mapper;

import com.icei.domain.BrandHot;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BrandHotMapper {
	
	
	/**
	 * 查询是否存在重复值
	 * @param goodsid
	 * @return
	 */
	int selectBygoodsid(@Param("goodsid")int goodsid);
    /**
     * 
     * 
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_hot
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int deleteByPrimaryKey(@Param("hotId")Integer hotId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_hot
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insert(BrandHot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_hot
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insertSelective(BrandHot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_hot
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    BrandHot selectByPrimaryKey(Integer hotId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_hot
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int updateByPrimaryKeySelective(BrandHot record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_hot
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int updateByPrimaryKey(BrandHot record);

    /**
     * 店铺热门
     * @return
     */
    List<BrandHot> getBrandHotAll(@Param("brandId")Integer brandId);
    /**
     * 查询全部
     * @param hotId
     * @return
     */
    List<BrandHot> getAllmsg(@Param("hotid")int hotid,@Param("page")int page,@Param("limit")int limit);
    
    int getAllmsgCount(@Param("hotid")Integer hotid);
    
    
}