package com.icei.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.icei.domain.BrandAudit;

public interface BrandAuditMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_audit
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int deleteByPrimaryKey(Integer brandId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_audit
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insert(BrandAudit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_audit
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insertSelective(BrandAudit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_audit
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    BrandAudit selectByPrimaryKey(Integer brandId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_audit
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int updateByPrimaryKeySelective(BrandAudit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_audit
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int updateByPrimaryKey(BrandAudit record);
    //分页查询
    List<BrandAudit> getBrandAuditPage(@Param("page")Integer page,@Param("pageSize")Integer pageSize,
    		@Param("id")Integer id,@Param("val")String val,@Param("statusId")Integer statusId);
    //查询总条数
    int getCount(@Param("id")Integer id,@Param("val")String val,@Param("statusId")Integer statusId);
    //id查询是否处理
    int getBrandStatus(@Param("brandId")Integer brandId);
    //查询是否通过审核
    BrandAudit getAuditSerial(@Param("serial")String serial,@Param("phone")String phone);
}