package com.icei.mapper;

import com.icei.domain.BrandPowerRole;

public interface BrandPowerRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_power_role
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int deleteByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_power_role
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insert(BrandPowerRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_power_role
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insertSelective(BrandPowerRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_power_role
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    BrandPowerRole selectByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_power_role
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int updateByPrimaryKeySelective(BrandPowerRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_power_role
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int updateByPrimaryKey(BrandPowerRole record);
}