package com.icei.mapper;

import java.util.List;

import com.icei.domain.BrandShow;

public interface BrandShowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_show
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int deleteByPrimaryKey(Integer showId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_show
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insert(BrandShow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_show
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insertSelective(BrandShow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_show
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    BrandShow selectByPrimaryKey(Integer showId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_show
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int updateByPrimaryKeySelective(BrandShow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_show
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int updateByPrimaryKey(BrandShow record);
    
    List<BrandShow> getByBrandId(Integer brandId);
}