package com.icei.mapper;

import com.icei.domain.BuyersShowRelation;

public interface BuyersShowRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyers_show_relation
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insert(BuyersShowRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buyers_show_relation
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insertSelective(BuyersShowRelation record);
}