package com.icei.mapper;

import java.util.List;
import java.util.Map;

import com.icei.domain.Discounts;

public interface DiscountsMapper {
	/**
	 * 根据店铺id查询优惠券
	 * @param brandId
	 * @return
	 */
	List<Discounts> GetDiscount(Map<String,Object> map);
	/**
	 * 根据店铺id查询优惠券总条数
	 * @param map
	 * @return
	 */
	int GetAllCounnt(Map<String,Object> map);
	//店铺方法
	/**
	 * 根据店铺id查询优惠券
	 * @param brandId
	 * @return
	 */
	List<Discounts> byBrandIdGetDiscount(Map<String,Object> map);
	/**
	 * 根据店铺id查询优惠券总条数
	 * @param map
	 * @return
	 */
	int byBrandIdGetAllCounnt(Map<String,Object> map);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discounts
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int deleteByPrimaryKey(Integer discountsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discounts
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insert(Discounts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discounts
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insertSelective(Discounts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discounts
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    Discounts selectByPrimaryKey(Integer discountsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discounts
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int updateByPrimaryKeySelective(Discounts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table discounts
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int updateByPrimaryKey(Discounts record);
}