package com.icei.mapper;

import com.icei.domain.DiyMould;

public interface DiyMouldMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diy_mould
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int deleteByPrimaryKey(Integer diyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diy_mould
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insert(DiyMould record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diy_mould
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insertSelective(DiyMould record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diy_mould
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    DiyMould selectByPrimaryKey(Integer diyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diy_mould
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int updateByPrimaryKeySelective(DiyMould record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table diy_mould
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int updateByPrimaryKey(DiyMould record);
}