package com.icei.mapper;

import com.icei.domain.GeneralizeAddress;

public interface GeneralizeAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generalize_address
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int deleteByPrimaryKey(Integer addressId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generalize_address
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insert(GeneralizeAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generalize_address
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insertSelective(GeneralizeAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generalize_address
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    GeneralizeAddress selectByPrimaryKey(Integer addressId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generalize_address
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int updateByPrimaryKeySelective(GeneralizeAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table generalize_address
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int updateByPrimaryKey(GeneralizeAddress record);
}