package com.icei.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.icei.domain.GoodsModel;

public interface GoodsModelMapper {
	
	/**
	 * 根据商品id得到商品model
	 * @param goodsId
	 * @return
	 */
	List<GoodsModel> ByGoodIdGetGoodsModel(@Param("goodsId")int goodsId);
	/**
	 * 分页+条件+全部查询 
	 * @param map
	 * @return
	 */
	List<GoodsModel> getAll(Map<String,Object> map);
	/**
	 * 分页+条件+全部查询条数
	 * @param map
	 * @return
	 */
	int getCount(Map<String,Object> map);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_model
     *
     * @mbg.generated Mon Apr 30 02:41:42 CST 2018
     */
    int deleteByPrimaryKey(Integer modelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_model
     *
     * @mbg.generated Mon Apr 30 02:41:42 CST 2018
     */
    int insert(GoodsModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_model
     *
     * @mbg.generated Mon Apr 30 02:41:42 CST 2018
     */
    int insertSelective(GoodsModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_model
     *
     * @mbg.generated Mon Apr 30 02:41:42 CST 2018
     */
    GoodsModel selectByPrimaryKey(Integer modelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_model
     *
     * @mbg.generated Mon Apr 30 02:41:42 CST 2018
     */
    int updateByPrimaryKeySelective(GoodsModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_model
     *
     * @mbg.generated Mon Apr 30 02:41:42 CST 2018
     */
    int updateByPrimaryKey(GoodsModel record);
}