package com.icei.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.icei.domain.GoodsType;

public interface GoodsTypeMapper {
	
	/**
	 * 得到全部商品类别信息-分页
	 * @param page
	 * @param pageSize
	 * @return
	 */
	List<GoodsType> getAllGoodsType(Map<String,Object> map);
	/**
	 * 获取所有分类
	 * @return
	 */
	List<GoodsType> getGoodsTypeAll();
	List<GoodsType> getAllGoodsTypes();
	
	/**
	 * 得到全部数量
	 * @return
	 */
	int getCount(Map<String,Object> map);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_type
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int deleteByPrimaryKey(Integer typeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_type
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insert(GoodsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_type
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insertSelective(GoodsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_type
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    GoodsType selectByPrimaryKey(Integer typeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_type
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int updateByPrimaryKeySelective(GoodsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_type
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int updateByPrimaryKey(GoodsType record);
}