package com.icei.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.icei.domain.GoodsSize;

public interface GoodsSizeMapper {
	/**
	 *  根据商品ID得到商品尺寸----宇
	 * @param goodsId
	 * @return
	 */
	List<GoodsSize> byGoodsId(@Param("goodsId")int goodsId); 
	/**
	 *  查询全部，带分页，带条件查询
	 * @param map
	 * @return
	 */
	List<GoodsSize> getAll(Map<String,Object> map); 
	/**
	 * 查询全部条数
	 * @param map
	 * @return
	 */
	int getCount(Map<String,Object> map);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_size
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int deleteByPrimaryKey(Integer sizeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_size
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insert(GoodsSize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_size
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insertSelective(GoodsSize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_size
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    GoodsSize selectByPrimaryKey(Integer sizeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_size
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int updateByPrimaryKeySelective(GoodsSize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_size
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int updateByPrimaryKey(GoodsSize record);
}