package com.icei.mapper;

import org.apache.ibatis.annotations.Param;

import com.icei.domain.LikeGoods;

public interface LikeGoodsMapper {
	/**
	 * 取消商品收藏
	 * @param userId
	 * @param goodsId
	 * @return
	 */
	int cancelLikeGoods(@Param("userId")int userId,@Param("goodsId")int goodsId);
	/**
	 * 验证是否已经收藏
	 * @param record
	 * @return
	 */
	int search(LikeGoods record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like_goods
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insert(LikeGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like_goods
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insertSelective(LikeGoods record);
}