package com.icei.mapper;

import org.apache.ibatis.annotations.Param;

import com.icei.domain.LikeBrand;

public interface LikeBrandMapper {
	
	/**
	 * 取消收藏
	 * @param userId
	 * @param brandId
	 * @return
	 */
	int cancelLikeBrand(@Param("userId")int userId,@Param("brandId")int brandId);
	
	/**
	 * 验证是否已经收藏该店铺
	 * @param record
	 * @return
	 */
	int verification(LikeBrand record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like_brand
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int deleteByPrimaryKey(Integer brandId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like_brand
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insert(LikeBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like_brand
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insertSelective(LikeBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like_brand
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    LikeBrand selectByPrimaryKey(Integer brandId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like_brand
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int updateByPrimaryKeySelective(LikeBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table like_brand
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int updateByPrimaryKey(LikeBrand record);
}