package com.icei.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.icei.domain.OrderAssess;
public interface OrderAssessMapper {
	/**
	 * 通过商品ID获取该商的所有评论
	 * @return
	 */
	List<OrderAssess> byGoodsIdGetInfo(@Param("goodsId")int goodsId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_assess
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int deleteByPrimaryKey(Integer assessId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_assess
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insert(OrderAssess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_assess
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insertSelective(OrderAssess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_assess
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    OrderAssess selectByPrimaryKey(Integer assessId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_assess
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int updateByPrimaryKeySelective(OrderAssess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_assess
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int updateByPrimaryKey(OrderAssess record);
}