package com.icei.mapper;

import com.icei.domain.PowerAuthority;

public interface PowerAuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_ authority
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int deleteByPrimaryKey(Integer authorityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_ authority
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insert(PowerAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_ authority
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insertSelective(PowerAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_ authority
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    PowerAuthority selectByPrimaryKey(Integer authorityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_ authority
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int updateByPrimaryKeySelective(PowerAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table power_ authority
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int updateByPrimaryKey(PowerAuthority record);
}