package com.icei.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.icei.domain.PowerRoleAuth;

public interface PowerRoleAuthMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table power_role_auth
	 *
	 * @mbg.generated Thu Apr 19 10:27:54 CST 2018
	 */
	int insert(PowerRoleAuth record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table power_role_auth
	 *
	 * @mbg.generated Thu Apr 19 10:27:54 CST 2018
	 */
	int insertSelective(PowerRoleAuth record);

	List<PowerRoleAuth> getRelationByRoleId(int roleId);

	int delete(PowerRoleAuth powerRoleAuth);
}