package com.icei.mapper;

import java.util.List;

import com.icei.domain.Slideshow;

public interface SlideshowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slideshow
     *
     * @mbg.generated Fri Apr 27 21:19:30 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slideshow
     *
     * @mbg.generated Fri Apr 27 21:19:30 CST 2018
     */
    int insert(Slideshow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slideshow
     *
     * @mbg.generated Fri Apr 27 21:19:30 CST 2018
     */
    int insertSelective(Slideshow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slideshow
     *
     * @mbg.generated Fri Apr 27 21:19:30 CST 2018
     */
    Slideshow selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slideshow
     *
     * @mbg.generated Fri Apr 27 21:19:30 CST 2018
     */
    int updateByPrimaryKeySelective(Slideshow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table slideshow
     *
     * @mbg.generated Fri Apr 27 21:19:30 CST 2018
     */
    int updateByPrimaryKey(Slideshow record);
    /**
     * 查询所有轮播
     * @return
     */
    List<Slideshow> getSlideAll();
}