package com.icei.mapper;

import java.util.List;
import java.util.Map;

import com.icei.domain.SystemGeneralize;

public interface SystemGeneralizeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_generalize
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int deleteByPrimaryKey(Integer generalizeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_generalize
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insert(SystemGeneralize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_generalize
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insertSelective(SystemGeneralize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_generalize
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    SystemGeneralize selectByPrimaryKey(Integer generalizeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_generalize
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int updateByPrimaryKeySelective(SystemGeneralize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table system_generalize
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int updateByPrimaryKey(SystemGeneralize record);
    
    /**
     * 查询全部推广信息+分页
     * @return List<SystemGeneralize>
     */
    List<SystemGeneralize> getAllMessage(Map<String, Object> map);
    
    /**
     * 查询总条数
     * @return
     */
    int selectByMaxCount(Map<String, Object> map);
    
    SystemGeneralize selectBybrandName(String name);
}