package com.icei.mapper;

import com.icei.domain.UserRelation;

public interface UserRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_relation
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insert(UserRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_relation
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    int insertSelective(UserRelation record);
}