package com.icei.domain;

public class AssessImg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assess_img.img_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer imgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assess_img.assess_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer assessId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assess_img.img_path
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String imgPath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assess_img.img_id
     *
     * @return the value of assess_img.img_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getImgId() {
        return imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assess_img.img_id
     *
     * @param imgId the value for assess_img.img_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setImgId(Integer imgId) {
        this.imgId = imgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assess_img.assess_id
     *
     * @return the value of assess_img.assess_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getAssessId() {
        return assessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assess_img.assess_id
     *
     * @param assessId the value for assess_img.assess_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setAssessId(Integer assessId) {
        this.assessId = assessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assess_img.img_path
     *
     * @return the value of assess_img.img_path
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getImgPath() {
        return imgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assess_img.img_path
     *
     * @param imgPath the value for assess_img.img_path
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath;
    }
}