package com.icei.domain;

public class AssessTagRelation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assess_tag_relation.assess_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer assessId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assess_tag_relation.tag_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer tagId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assess_tag_relation.assess_id
     *
     * @return the value of assess_tag_relation.assess_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getAssessId() {
        return assessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assess_tag_relation.assess_id
     *
     * @param assessId the value for assess_tag_relation.assess_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setAssessId(Integer assessId) {
        this.assessId = assessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assess_tag_relation.tag_id
     *
     * @return the value of assess_tag_relation.tag_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assess_tag_relation.tag_id
     *
     * @param tagId the value for assess_tag_relation.tag_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }
}