package com.icei.domain;

public class AssessTag {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assess_tag.assess_tagID
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer assessTagid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column assess_tag.assess_tagName
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String assessTagname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assess_tag.assess_tagID
     *
     * @return the value of assess_tag.assess_tagID
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getAssessTagid() {
        return assessTagid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assess_tag.assess_tagID
     *
     * @param assessTagid the value for assess_tag.assess_tagID
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setAssessTagid(Integer assessTagid) {
        this.assessTagid = assessTagid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column assess_tag.assess_tagName
     *
     * @return the value of assess_tag.assess_tagName
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getAssessTagname() {
        return assessTagname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column assess_tag.assess_tagName
     *
     * @param assessTagname the value for assess_tag.assess_tagName
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setAssessTagname(String assessTagname) {
        this.assessTagname = assessTagname;
    }
}