package com.icei.domain;

public class AuditStatus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audit_status.status_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer statusId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audit_status.status_name
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String statusName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audit_status.status_id
     *
     * @return the value of audit_status.status_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getStatusId() {
        return statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audit_status.status_id
     *
     * @param statusId the value for audit_status.status_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audit_status.status_name
     *
     * @return the value of audit_status.status_name
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getStatusName() {
        return statusName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audit_status.status_name
     *
     * @param statusName the value for audit_status.status_name
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setStatusName(String statusName) {
        this.statusName = statusName;
    }
}