package com.icei.domain;

import java.util.Date;

public class Award {
	
	private UserDetail userDetail;
	
	private Template template;
	
	private AwardType awardType;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award.award_id
     *
     * @mbg.generated Sun May 20 11:21:13 CST 2018
     */
    private Integer awardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award.award_type_id
     *
     * @mbg.generated Sun May 20 11:21:13 CST 2018
     */
    private Integer awardTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award.discounts_id
     *
     * @mbg.generated Sun May 20 11:21:13 CST 2018
     */
    private Integer discountsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award.award_time
     *
     * @mbg.generated Sun May 20 11:21:13 CST 2018
     */
    private Date awardTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column award.user_id
     *
     * @mbg.generated Sun May 20 11:21:13 CST 2018
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column award.award_id
     *
     * @return the value of award.award_id
     *
     * @mbg.generated Sun May 20 11:21:13 CST 2018
     */
    public Integer getAwardId() {
        return awardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column award.award_id
     *
     * @param awardId the value for award.award_id
     *
     * @mbg.generated Sun May 20 11:21:13 CST 2018
     */
    public void setAwardId(Integer awardId) {
        this.awardId = awardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column award.award_type_id
     *
     * @return the value of award.award_type_id
     *
     * @mbg.generated Sun May 20 11:21:13 CST 2018
     */
    public Integer getAwardTypeId() {
        return awardTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column award.award_type_id
     *
     * @param awardTypeId the value for award.award_type_id
     *
     * @mbg.generated Sun May 20 11:21:13 CST 2018
     */
    public void setAwardTypeId(Integer awardTypeId) {
        this.awardTypeId = awardTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column award.discounts_id
     *
     * @return the value of award.discounts_id
     *
     * @mbg.generated Sun May 20 11:21:13 CST 2018
     */
    public Integer getDiscountsId() {
        return discountsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column award.discounts_id
     *
     * @param discountsId the value for award.discounts_id
     *
     * @mbg.generated Sun May 20 11:21:13 CST 2018
     */
    public void setDiscountsId(Integer discountsId) {
        this.discountsId = discountsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column award.award_time
     *
     * @return the value of award.award_time
     *
     * @mbg.generated Sun May 20 11:21:13 CST 2018
     */
    public Date getAwardTime() {
        return awardTime;
    }

    
    public AwardType getAwardType() {
		return awardType;
	}

	public void setAwardType(AwardType awardType) {
		this.awardType = awardType;
	}

	public UserDetail getUserDetail() {
		return userDetail;
	}

	public void setUserDetail(UserDetail userDetail) {
		this.userDetail = userDetail;
	}



	public Template getTemplate() {
		return template;
	}

	public void setTemplate(Template template) {
		this.template = template;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column award.award_time
     *
     * @param awardTime the value for award.award_time
     *
     * @mbg.generated Sun May 20 11:21:13 CST 2018
     */
    public void setAwardTime(Date awardTime) {
        this.awardTime = awardTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column award.user_id
     *
     * @return the value of award.user_id
     *
     * @mbg.generated Sun May 20 11:21:13 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column award.user_id
     *
     * @param userId the value for award.user_id
     *
     * @mbg.generated Sun May 20 11:21:13 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}