package com.icei.domain;

import java.util.Date;

public class Bill {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.bill_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer billId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.brand_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer brandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.strat_date
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Date stratDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.end_date
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Date endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.bill_money
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Float billMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.order_num
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer orderNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.bill_status
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String billStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.bill_id
     *
     * @return the value of bill.bill_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getBillId() {
        return billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.bill_id
     *
     * @param billId the value for bill.bill_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setBillId(Integer billId) {
        this.billId = billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.brand_id
     *
     * @return the value of bill.brand_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.brand_id
     *
     * @param brandId the value for bill.brand_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.strat_date
     *
     * @return the value of bill.strat_date
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Date getStratDate() {
        return stratDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.strat_date
     *
     * @param stratDate the value for bill.strat_date
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setStratDate(Date stratDate) {
        this.stratDate = stratDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.end_date
     *
     * @return the value of bill.end_date
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.end_date
     *
     * @param endDate the value for bill.end_date
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.bill_money
     *
     * @return the value of bill.bill_money
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Float getBillMoney() {
        return billMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.bill_money
     *
     * @param billMoney the value for bill.bill_money
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setBillMoney(Float billMoney) {
        this.billMoney = billMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.order_num
     *
     * @return the value of bill.order_num
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.order_num
     *
     * @param orderNum the value for bill.order_num
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.bill_status
     *
     * @return the value of bill.bill_status
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getBillStatus() {
        return billStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.bill_status
     *
     * @param billStatus the value for bill.bill_status
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setBillStatus(String billStatus) {
        this.billStatus = billStatus;
    }
}