package com.icei.domain;

public class BillOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_order.bill_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer billId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill_order.order_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer orderId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_order.bill_id
     *
     * @return the value of bill_order.bill_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getBillId() {
        return billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_order.bill_id
     *
     * @param billId the value for bill_order.bill_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setBillId(Integer billId) {
        this.billId = billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill_order.order_id
     *
     * @return the value of bill_order.order_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill_order.order_id
     *
     * @param orderId the value for bill_order.order_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
}