package com.icei.domain;

public class Brand {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.brand_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer brandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.brand_name
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String brandName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.icon_path
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String iconPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.brand_desc
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String brandDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.goods_num
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer goodsNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.goods_quality
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Float goodsQuality;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.server_attitude
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Float serverAttitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.like_count
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer likeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.brand_title
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String brandTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.brand_status
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer brandStatus;
    
    private BrandPrincipal brandPrincipal;
    
    

    public BrandPrincipal getBrandPrincipal() {
		return brandPrincipal;
	}

	public void setBrandPrincipal(BrandPrincipal brandPrincipal) {
		this.brandPrincipal = brandPrincipal;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.brand_id
     *
     * @return the value of brand.brand_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.brand_id
     *
     * @param brandId the value for brand.brand_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.brand_name
     *
     * @return the value of brand.brand_name
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.brand_name
     *
     * @param brandName the value for brand.brand_name
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.icon_path
     *
     * @return the value of brand.icon_path
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getIconPath() {
        return iconPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.icon_path
     *
     * @param iconPath the value for brand.icon_path
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setIconPath(String iconPath) {
        this.iconPath = iconPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.brand_desc
     *
     * @return the value of brand.brand_desc
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getBrandDesc() {
        return brandDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.brand_desc
     *
     * @param brandDesc the value for brand.brand_desc
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setBrandDesc(String brandDesc) {
        this.brandDesc = brandDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.goods_num
     *
     * @return the value of brand.goods_num
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getGoodsNum() {
        return goodsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.goods_num
     *
     * @param goodsNum the value for brand.goods_num
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setGoodsNum(Integer goodsNum) {
        this.goodsNum = goodsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.goods_quality
     *
     * @return the value of brand.goods_quality
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Float getGoodsQuality() {
        return goodsQuality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.goods_quality
     *
     * @param goodsQuality the value for brand.goods_quality
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setGoodsQuality(Float goodsQuality) {
        this.goodsQuality = goodsQuality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.server_attitude
     *
     * @return the value of brand.server_attitude
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Float getServerAttitude() {
        return serverAttitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.server_attitude
     *
     * @param serverAttitude the value for brand.server_attitude
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setServerAttitude(Float serverAttitude) {
        this.serverAttitude = serverAttitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.like_count
     *
     * @return the value of brand.like_count
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.like_count
     *
     * @param likeCount the value for brand.like_count
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.brand_title
     *
     * @return the value of brand.brand_title
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getBrandTitle() {
        return brandTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.brand_title
     *
     * @param brandTitle the value for brand.brand_title
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setBrandTitle(String brandTitle) {
        this.brandTitle = brandTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.brand_status
     *
     * @return the value of brand.brand_status
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getBrandStatus() {
        return brandStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.brand_status
     *
     * @param brandStatus the value for brand.brand_status
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setBrandStatus(Integer brandStatus) {
        this.brandStatus = brandStatus;
    }
}