package com.icei.domain;

public class BrandPrincipal {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_principal.audit_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer auditId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_principal.audit_name
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String auditName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_principal.audit_tel
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String auditTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_principal.audit_address
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String auditAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_principal.audit_idCad
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Long auditIdcad;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_principal.audit_idCad_ImgFront
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String auditIdcadImgfront;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_principal.audit_idCad_ImgBack
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String auditIdcadImgback;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_principal.audit_id
     *
     * @return the value of brand_principal.audit_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getAuditId() {
        return auditId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_principal.audit_id
     *
     * @param auditId the value for brand_principal.audit_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setAuditId(Integer auditId) {
        this.auditId = auditId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_principal.audit_name
     *
     * @return the value of brand_principal.audit_name
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getAuditName() {
        return auditName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_principal.audit_name
     *
     * @param auditName the value for brand_principal.audit_name
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setAuditName(String auditName) {
        this.auditName = auditName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_principal.audit_tel
     *
     * @return the value of brand_principal.audit_tel
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getAuditTel() {
        return auditTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_principal.audit_tel
     *
     * @param auditTel the value for brand_principal.audit_tel
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setAuditTel(String auditTel) {
        this.auditTel = auditTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_principal.audit_address
     *
     * @return the value of brand_principal.audit_address
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getAuditAddress() {
        return auditAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_principal.audit_address
     *
     * @param auditAddress the value for brand_principal.audit_address
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setAuditAddress(String auditAddress) {
        this.auditAddress = auditAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_principal.audit_idCad
     *
     * @return the value of brand_principal.audit_idCad
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Long getAuditIdcad() {
        return auditIdcad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_principal.audit_idCad
     *
     * @param auditIdcad the value for brand_principal.audit_idCad
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setAuditIdcad(Long auditIdcad) {
        this.auditIdcad = auditIdcad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_principal.audit_idCad_ImgFront
     *
     * @return the value of brand_principal.audit_idCad_ImgFront
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getAuditIdcadImgfront() {
        return auditIdcadImgfront;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_principal.audit_idCad_ImgFront
     *
     * @param auditIdcadImgfront the value for brand_principal.audit_idCad_ImgFront
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setAuditIdcadImgfront(String auditIdcadImgfront) {
        this.auditIdcadImgfront = auditIdcadImgfront;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_principal.audit_idCad_ImgBack
     *
     * @return the value of brand_principal.audit_idCad_ImgBack
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getAuditIdcadImgback() {
        return auditIdcadImgback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_principal.audit_idCad_ImgBack
     *
     * @param auditIdcadImgback the value for brand_principal.audit_idCad_ImgBack
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setAuditIdcadImgback(String auditIdcadImgback) {
        this.auditIdcadImgback = auditIdcadImgback;
    }
}