package com.icei.domain;

import java.util.Date;

public class BrandAdminSublevel {
	
	private BrandPowerRole  brandPowerRole;
	
	private Date roleCreateTime;
	
	private Date roleUpdateTime;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_admin_sublevel.sublevel_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer sublevelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_admin_sublevel.sub_code
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String subCode;
    
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_admin_sublevel.sub_pwd
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String subPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_admin_sublevel.admin_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_admin_sublevel.brand_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer brandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_admin_sublevel.sub_name
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String subName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_admin_sublevel.role_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer roleId;

    
    public Date getRoleCreateTime() {
		return roleCreateTime;
	}

	public void setRoleCreateTime(Date roleCreateTime) {
		this.roleCreateTime = roleCreateTime;
	}

	public Date getRoleUpdateTime() {
		return roleUpdateTime;
	}

	public void setRoleUpdateTime(Date roleUpdateTime) {
		this.roleUpdateTime = roleUpdateTime;
	}

	public BrandPowerRole getBrandPowerRole() {
		return brandPowerRole;
	}

	public void setBrandPowerRole(BrandPowerRole brandPowerRole) {
		this.brandPowerRole = brandPowerRole;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_admin_sublevel.sublevel_id
     *
     * @return the value of brand_admin_sublevel.sublevel_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getSublevelId() {
        return sublevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_admin_sublevel.sublevel_id
     *
     * @param sublevelId the value for brand_admin_sublevel.sublevel_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setSublevelId(Integer sublevelId) {
        this.sublevelId = sublevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_admin_sublevel.sub_code
     *
     * @return the value of brand_admin_sublevel.sub_code
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getSubCode() {
        return subCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_admin_sublevel.sub_code
     *
     * @param subCode the value for brand_admin_sublevel.sub_code
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setSubCode(String subCode) {
        this.subCode = subCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_admin_sublevel.sub_pwd
     *
     * @return the value of brand_admin_sublevel.sub_pwd
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getSubPwd() {
        return subPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_admin_sublevel.sub_pwd
     *
     * @param subPwd the value for brand_admin_sublevel.sub_pwd
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setSubPwd(String subPwd) {
        this.subPwd = subPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_admin_sublevel.admin_id
     *
     * @return the value of brand_admin_sublevel.admin_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_admin_sublevel.admin_id
     *
     * @param adminId the value for brand_admin_sublevel.admin_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_admin_sublevel.brand_id
     *
     * @return the value of brand_admin_sublevel.brand_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_admin_sublevel.brand_id
     *
     * @param brandId the value for brand_admin_sublevel.brand_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_admin_sublevel.sub_name
     *
     * @return the value of brand_admin_sublevel.sub_name
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getSubName() {
        return subName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_admin_sublevel.sub_name
     *
     * @param subName the value for brand_admin_sublevel.sub_name
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setSubName(String subName) {
        this.subName = subName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_admin_sublevel.role_id
     *
     * @return the value of brand_admin_sublevel.role_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_admin_sublevel.role_id
     *
     * @param roleId the value for brand_admin_sublevel.role_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}