package com.icei.domain;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class BrandAudit {
	private String statusName;//状态
    public String getStatusName() {
		return statusName;
	}

	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_audit.brand_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer brandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_audit.brand_name
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String brandName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_audit.brand_photo
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String brandPhoto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_audit.brand_intro
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String brandIntro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_audit.audit_name
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String auditName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_audit.audit_tel
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String auditTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_audit.audit_address
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String auditAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_audit.audit_idCad
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Long auditIdcad;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_audit.audit_idCad_ImgFront
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String auditIdcadImgfront;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_audit.audit_idCad_ImgBack
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String auditIdcadImgback;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_audit.audit_time
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    @DateTimeFormat(pattern="yyyy-MM-dd hh:mm:ss")
    private Date auditTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_audit.audit_pass_time
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    @DateTimeFormat(pattern="yyyy-MM-dd hh:mm:ss")
    private Date auditPassTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_audit.audit_status_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer auditStatusId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_audit.audit_serial
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String auditSerial;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_audit.brand_id
     *
     * @return the value of brand_audit.brand_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_audit.brand_id
     *
     * @param brandId the value for brand_audit.brand_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_audit.brand_name
     *
     * @return the value of brand_audit.brand_name
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_audit.brand_name
     *
     * @param brandName the value for brand_audit.brand_name
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_audit.brand_photo
     *
     * @return the value of brand_audit.brand_photo
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getBrandPhoto() {
        return brandPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_audit.brand_photo
     *
     * @param brandPhoto the value for brand_audit.brand_photo
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setBrandPhoto(String brandPhoto) {
        this.brandPhoto = brandPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_audit.brand_intro
     *
     * @return the value of brand_audit.brand_intro
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getBrandIntro() {
        return brandIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_audit.brand_intro
     *
     * @param brandIntro the value for brand_audit.brand_intro
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setBrandIntro(String brandIntro) {
        this.brandIntro = brandIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_audit.audit_name
     *
     * @return the value of brand_audit.audit_name
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getAuditName() {
        return auditName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_audit.audit_name
     *
     * @param auditName the value for brand_audit.audit_name
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setAuditName(String auditName) {
        this.auditName = auditName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_audit.audit_tel
     *
     * @return the value of brand_audit.audit_tel
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getAuditTel() {
        return auditTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_audit.audit_tel
     *
     * @param auditTel the value for brand_audit.audit_tel
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setAuditTel(String auditTel) {
        this.auditTel = auditTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_audit.audit_address
     *
     * @return the value of brand_audit.audit_address
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getAuditAddress() {
        return auditAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_audit.audit_address
     *
     * @param auditAddress the value for brand_audit.audit_address
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setAuditAddress(String auditAddress) {
        this.auditAddress = auditAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_audit.audit_idCad
     *
     * @return the value of brand_audit.audit_idCad
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Long getAuditIdcad() {
        return auditIdcad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_audit.audit_idCad
     *
     * @param auditIdcad the value for brand_audit.audit_idCad
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setAuditIdcad(Long auditIdcad) {
        this.auditIdcad = auditIdcad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_audit.audit_idCad_ImgFront
     *
     * @return the value of brand_audit.audit_idCad_ImgFront
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getAuditIdcadImgfront() {
        return auditIdcadImgfront;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_audit.audit_idCad_ImgFront
     *
     * @param auditIdcadImgfront the value for brand_audit.audit_idCad_ImgFront
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setAuditIdcadImgfront(String auditIdcadImgfront) {
        this.auditIdcadImgfront = auditIdcadImgfront;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_audit.audit_idCad_ImgBack
     *
     * @return the value of brand_audit.audit_idCad_ImgBack
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getAuditIdcadImgback() {
        return auditIdcadImgback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_audit.audit_idCad_ImgBack
     *
     * @param auditIdcadImgback the value for brand_audit.audit_idCad_ImgBack
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setAuditIdcadImgback(String auditIdcadImgback) {
        this.auditIdcadImgback = auditIdcadImgback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_audit.audit_time
     *
     * @return the value of brand_audit.audit_time
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Date getAuditTime() {
        return auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_audit.audit_time
     *
     * @param auditTime the value for brand_audit.audit_time
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setAuditTime(Date auditTime) {
        this.auditTime = auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_audit.audit_pass_time
     *
     * @return the value of brand_audit.audit_pass_time
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Date getAuditPassTime() {
        return auditPassTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_audit.audit_pass_time
     *
     * @param auditPassTime the value for brand_audit.audit_pass_time
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setAuditPassTime(Date auditPassTime) {
        this.auditPassTime = auditPassTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_audit.audit_status_id
     *
     * @return the value of brand_audit.audit_status_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getAuditStatusId() {
        return auditStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_audit.audit_status_id
     *
     * @param auditStatusId the value for brand_audit.audit_status_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setAuditStatusId(Integer auditStatusId) {
        this.auditStatusId = auditStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_audit.audit_serial
     *
     * @return the value of brand_audit.audit_serial
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getAuditSerial() {
        return auditSerial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_audit.audit_serial
     *
     * @param auditSerial the value for brand_audit.audit_serial
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setAuditSerial(String auditSerial) {
        this.auditSerial = auditSerial;
    }
}