package com.icei.domain;

public class BrandShow {
	private String describe;
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column brand_show.show_id
	 *
	 * @mbg.generated Thu Apr 19 10:27:54 CST 2018
	 */
	private Integer showId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column brand_show.brand_id
	 *
	 * @mbg.generated Thu Apr 19 10:27:54 CST 2018
	 */
	private Integer brandId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column brand_show.img_path
	 *
	 * @mbg.generated Thu Apr 19 10:27:54 CST 2018
	 */
	private String imgPath;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column brand_show.show_id
	 *
	 * @return the value of brand_show.show_id
	 *
	 * @mbg.generated Thu Apr 19 10:27:54 CST 2018
	 */
	public Integer getShowId() {
		return showId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column brand_show.show_id
	 *
	 * @param showId
	 *            the value for brand_show.show_id
	 *
	 * @mbg.generated Thu Apr 19 10:27:54 CST 2018
	 */
	public void setShowId(Integer showId) {
		this.showId = showId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column brand_show.brand_id
	 *
	 * @return the value of brand_show.brand_id
	 *
	 * @mbg.generated Thu Apr 19 10:27:54 CST 2018
	 */
	public Integer getBrandId() {
		return brandId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column brand_show.brand_id
	 *
	 * @param brandId
	 *            the value for brand_show.brand_id
	 *
	 * @mbg.generated Thu Apr 19 10:27:54 CST 2018
	 */
	public void setBrandId(Integer brandId) {
		this.brandId = brandId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column brand_show.img_path
	 *
	 * @return the value of brand_show.img_path
	 *
	 * @mbg.generated Thu Apr 19 10:27:54 CST 2018
	 */
	public String getImgPath() {
		return imgPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column brand_show.img_path
	 *
	 * @param imgPath
	 *            the value for brand_show.img_path
	 *
	 * @mbg.generated Thu Apr 19 10:27:54 CST 2018
	 */
	public void setImgPath(String imgPath) {
		this.imgPath = imgPath;
	}

	public String getDescribe() {
		return describe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column brand_show.img_path
	 *
	 * @param imgPath
	 *            the value for brand_show.img_path
	 *
	 * @mbg.generated Thu Apr 19 10:27:54 CST 2018
	 */
	public void setDescribe(String describe) {
		this.describe = describe;
	}
}