package com.icei.domain;

public class BrandAdmin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_admin.brand_adm_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer brandAdmId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_admin.admin_code
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String adminCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_admin.pwd
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_admin.principal_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer principalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_admin.brand_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer brandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_admin.role_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_admin.brand_adm_id
     *
     * @return the value of brand_admin.brand_adm_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getBrandAdmId() {
        return brandAdmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_admin.brand_adm_id
     *
     * @param brandAdmId the value for brand_admin.brand_adm_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setBrandAdmId(Integer brandAdmId) {
        this.brandAdmId = brandAdmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_admin.admin_code
     *
     * @return the value of brand_admin.admin_code
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getAdminCode() {
        return adminCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_admin.admin_code
     *
     * @param adminCode the value for brand_admin.admin_code
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setAdminCode(String adminCode) {
        this.adminCode = adminCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_admin.pwd
     *
     * @return the value of brand_admin.pwd
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_admin.pwd
     *
     * @param pwd the value for brand_admin.pwd
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_admin.principal_id
     *
     * @return the value of brand_admin.principal_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getPrincipalId() {
        return principalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_admin.principal_id
     *
     * @param principalId the value for brand_admin.principal_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setPrincipalId(Integer principalId) {
        this.principalId = principalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_admin.brand_id
     *
     * @return the value of brand_admin.brand_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_admin.brand_id
     *
     * @param brandId the value for brand_admin.brand_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_admin.role_id
     *
     * @return the value of brand_admin.role_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_admin.role_id
     *
     * @param roleId the value for brand_admin.role_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}