package com.icei.domain;

import java.util.Date;

public class Discounts {
	
	private String discountsName;
	private int templateId;
    public int getTemplateId() {
		return templateId;
	}

	public void setTemplateId(int templateId) {
		this.templateId = templateId;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discounts.discounts_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer discountsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discounts.discounts_start_time
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Date discountsStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discounts.discounts_end_time
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Date discountsEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discounts.get_time
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Date getTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discounts.discounts_scope
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer discountsScope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discounts.brand_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer brandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discounts.big_money
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer bigMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discounts.small_money
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer smallMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discounts.user_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column discounts.template_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Template template;
	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discounts.discounts_id
     *
     * @return the value of discounts.discounts_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getDiscountsId() {
        return discountsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discounts.discounts_id
     *
     * @param discountsId the value for discounts.discounts_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setDiscountsId(Integer discountsId) {
        this.discountsId = discountsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discounts.discounts_start_time
     *
     * @return the value of discounts.discounts_start_time
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Date getDiscountsStartTime() {
        return discountsStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discounts.discounts_start_time
     *
     * @param discountsStartTime the value for discounts.discounts_start_time
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setDiscountsStartTime(Date discountsStartTime) {
        this.discountsStartTime = discountsStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discounts.discounts_end_time
     *
     * @return the value of discounts.discounts_end_time
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Date getDiscountsEndTime() {
        return discountsEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discounts.discounts_end_time
     *
     * @param discountsEndTime the value for discounts.discounts_end_time
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setDiscountsEndTime(Date discountsEndTime) {
        this.discountsEndTime = discountsEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discounts.get_time
     *
     * @return the value of discounts.get_time
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Date getGetTime() {
        return getTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discounts.get_time
     *
     * @param getTime the value for discounts.get_time
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setGetTime(Date getTime) {
        this.getTime = getTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discounts.discounts_scope
     *
     * @return the value of discounts.discounts_scope
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getDiscountsScope() {
        return discountsScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discounts.discounts_scope
     *
     * @param discountsScope the value for discounts.discounts_scope
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setDiscountsScope(Integer discountsScope) {
        this.discountsScope = discountsScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discounts.brand_id
     *
     * @return the value of discounts.brand_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discounts.brand_id
     *
     * @param brandId the value for discounts.brand_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discounts.big_money
     *
     * @return the value of discounts.big_money
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getBigMoney() {
        return bigMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discounts.big_money
     *
     * @param bigMoney the value for discounts.big_money
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setBigMoney(Integer bigMoney) {
        this.bigMoney = bigMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discounts.small_money
     *
     * @return the value of discounts.small_money
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getSmallMoney() {
        return smallMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discounts.small_money
     *
     * @param smallMoney the value for discounts.small_money
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setSmallMoney(Integer smallMoney) {
        this.smallMoney = smallMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column discounts.user_id
     *
     * @return the value of discounts.user_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column discounts.user_id
     *
     * @param userId the value for discounts.user_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

	public Template getTemplate() {
		return template;
	}

	public void setTemplate(Template template) {
		this.template = template;
	}

	public String getDiscountsName() {
		return discountsName;
	}

	public void setDiscountsName(String discountsName) {
		this.discountsName = discountsName;
	}
}