package com.icei.domain;

public class DiyMould {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diy_mould.diy_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer diyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diy_mould.mould_img
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String mouldImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diy_mould.mould_back
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String mouldBack;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diy_mould.diy_id
     *
     * @return the value of diy_mould.diy_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getDiyId() {
        return diyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diy_mould.diy_id
     *
     * @param diyId the value for diy_mould.diy_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setDiyId(Integer diyId) {
        this.diyId = diyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diy_mould.mould_img
     *
     * @return the value of diy_mould.mould_img
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getMouldImg() {
        return mouldImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diy_mould.mould_img
     *
     * @param mouldImg the value for diy_mould.mould_img
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setMouldImg(String mouldImg) {
        this.mouldImg = mouldImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diy_mould.mould_back
     *
     * @return the value of diy_mould.mould_back
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getMouldBack() {
        return mouldBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diy_mould.mould_back
     *
     * @param mouldBack the value for diy_mould.mould_back
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setMouldBack(String mouldBack) {
        this.mouldBack = mouldBack;
    }
}