package com.icei.domain;

public class EcommendAward {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecommend_award.award_id
     *
     * @mbg.generated Sun May 20 11:21:13 CST 2018
     */
    private Integer awardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecommend_award.discount_template_id
     *
     * @mbg.generated Sun May 20 11:21:13 CST 2018
     */
    private Integer discountTemplateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecommend_award.user_id
     *
     * @mbg.generated Sun May 20 11:21:13 CST 2018
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecommend_award.award_id
     *
     * @return the value of ecommend_award.award_id
     *
     * @mbg.generated Sun May 20 11:21:13 CST 2018
     */
    public Integer getAwardId() {
        return awardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecommend_award.award_id
     *
     * @param awardId the value for ecommend_award.award_id
     *
     * @mbg.generated Sun May 20 11:21:13 CST 2018
     */
    public void setAwardId(Integer awardId) {
        this.awardId = awardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecommend_award.discount_template_id
     *
     * @return the value of ecommend_award.discount_template_id
     *
     * @mbg.generated Sun May 20 11:21:13 CST 2018
     */
    public Integer getDiscountTemplateId() {
        return discountTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecommend_award.discount_template_id
     *
     * @param discountTemplateId the value for ecommend_award.discount_template_id
     *
     * @mbg.generated Sun May 20 11:21:13 CST 2018
     */
    public void setDiscountTemplateId(Integer discountTemplateId) {
        this.discountTemplateId = discountTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecommend_award.user_id
     *
     * @return the value of ecommend_award.user_id
     *
     * @mbg.generated Sun May 20 11:21:13 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecommend_award.user_id
     *
     * @param userId the value for ecommend_award.user_id
     *
     * @mbg.generated Sun May 20 11:21:13 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}