package com.icei.domain;

public class GeneralizeAddress {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generalize_address.address_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer addressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column generalize_address.generalize_address
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String generalizeAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generalize_address.address_id
     *
     * @return the value of generalize_address.address_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generalize_address.address_id
     *
     * @param addressId the value for generalize_address.address_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column generalize_address.generalize_address
     *
     * @return the value of generalize_address.generalize_address
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getGeneralizeAddress() {
        return generalizeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column generalize_address.generalize_address
     *
     * @param generalizeAddress the value for generalize_address.generalize_address
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setGeneralizeAddress(String generalizeAddress) {
        this.generalizeAddress = generalizeAddress;
    }
}