package com.icei.domain;

public class GoodsMedia {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_media.intro_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer introId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_media.goods_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_media.intro_type
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String introType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_media.intro_path
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String introPath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_media.intro_id
     *
     * @return the value of goods_media.intro_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    
    public BrandGoods brandGoods;
    
    
    public BrandGoods getBrandGoods() {
		return brandGoods;
	}

	public void setBrandGoods(BrandGoods brandGoods) {
		this.brandGoods = brandGoods;
	}

	public Integer getIntroId() {
        return introId;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_media.intro_id
     *
     * @param introId the value for goods_media.intro_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setIntroId(Integer introId) {
        this.introId = introId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_media.goods_id
     *
     * @return the value of goods_media.goods_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_media.goods_id
     *
     * @param goodsId the value for goods_media.goods_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_media.intro_type
     *
     * @return the value of goods_media.intro_type
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getIntroType() {
        return introType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_media.intro_type
     *
     * @param introType the value for goods_media.intro_type
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setIntroType(String introType) {
        this.introType = introType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_media.intro_path
     *
     * @return the value of goods_media.intro_path
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getIntroPath() {
        return introPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_media.intro_path
     *
     * @param introPath the value for goods_media.intro_path
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setIntroPath(String introPath) {
        this.introPath = introPath;
    }
}