package com.icei.domain;

public class GoodsSize {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_size.size_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer sizeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_size.size_name
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String sizeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_size.goods_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer goodsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_size.size_id
     *
     * @return the value of goods_size.size_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getSizeId() {
        return sizeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_size.size_id
     *
     * @param sizeId the value for goods_size.size_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setSizeId(Integer sizeId) {
        this.sizeId = sizeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_size.size_name
     *
     * @return the value of goods_size.size_name
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getSizeName() {
        return sizeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_size.size_name
     *
     * @param sizeName the value for goods_size.size_name
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setSizeName(String sizeName) {
        this.sizeName = sizeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_size.goods_id
     *
     * @return the value of goods_size.goods_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_size.goods_id
     *
     * @param goodsId the value for goods_size.goods_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }
}