package com.icei.domain;

public class GoodsType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_type.type_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_type.type_name
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String typeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_type.type_img
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String typeImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_type.type_bgc
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String typeBgc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_type.type_icon
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String typeIcon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_type.type_id
     *
     * @return the value of goods_type.type_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_type.type_id
     *
     * @param typeId the value for goods_type.type_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_type.type_name
     *
     * @return the value of goods_type.type_name
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_type.type_name
     *
     * @param typeName the value for goods_type.type_name
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_type.type_img
     *
     * @return the value of goods_type.type_img
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getTypeImg() {
        return typeImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_type.type_img
     *
     * @param typeImg the value for goods_type.type_img
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setTypeImg(String typeImg) {
        this.typeImg = typeImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_type.type_bgc
     *
     * @return the value of goods_type.type_bgc
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getTypeBgc() {
        return typeBgc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_type.type_bgc
     *
     * @param typeBgc the value for goods_type.type_bgc
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setTypeBgc(String typeBgc) {
        this.typeBgc = typeBgc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_type.type_icon
     *
     * @return the value of goods_type.type_icon
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getTypeIcon() {
        return typeIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_type.type_icon
     *
     * @param typeIcon the value for goods_type.type_icon
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setTypeIcon(String typeIcon) {
        this.typeIcon = typeIcon;
    }
}