package com.icei.domain;

public class GoodsTypeDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_type_detail.type_detail_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer typeDetailId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_type_detail.type_detail_name
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String typeDetailName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_type_detail.type_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer typeId;

    
    private String typeName;
    
    public String getTypeName() {
		return typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_type_detail.type_detail_id
     *
     * @return the value of goods_type_detail.type_detail_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getTypeDetailId() {
        return typeDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_type_detail.type_detail_id
     *
     * @param typeDetailId the value for goods_type_detail.type_detail_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setTypeDetailId(Integer typeDetailId) {
        this.typeDetailId = typeDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_type_detail.type_detail_name
     *
     * @return the value of goods_type_detail.type_detail_name
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getTypeDetailName() {
        return typeDetailName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_type_detail.type_detail_name
     *
     * @param typeDetailName the value for goods_type_detail.type_detail_name
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setTypeDetailName(String typeDetailName) {
        this.typeDetailName = typeDetailName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_type_detail.type_id
     *
     * @return the value of goods_type_detail.type_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_type_detail.type_id
     *
     * @param typeId the value for goods_type_detail.type_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }
}