package com.icei.domain;

public class GoodsModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_model.model_id
     *
     * @mbg.generated Mon Apr 30 02:41:42 CST 2018
     */
    private Integer modelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_model.model_name
     *
     * @mbg.generated Mon Apr 30 02:41:42 CST 2018
     */
    private String modelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_model.model_img
     *
     * @mbg.generated Mon Apr 30 02:41:42 CST 2018
     */
    private String modelImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_model.goods_id
     *
     * @mbg.generated Mon Apr 30 02:41:42 CST 2018
     */
    private Integer goodsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_model.model_id
     *
     * @return the value of goods_model.model_id
     *
     * @mbg.generated Mon Apr 30 02:41:42 CST 2018
     */
    public Integer getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_model.model_id
     *
     * @param modelId the value for goods_model.model_id
     *
     * @mbg.generated Mon Apr 30 02:41:42 CST 2018
     */
    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_model.model_name
     *
     * @return the value of goods_model.model_name
     *
     * @mbg.generated Mon Apr 30 02:41:42 CST 2018
     */
    public String getModelName() {
        return modelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_model.model_name
     *
     * @param modelName the value for goods_model.model_name
     *
     * @mbg.generated Mon Apr 30 02:41:42 CST 2018
     */
    public void setModelName(String modelName) {
        this.modelName = modelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_model.model_img
     *
     * @return the value of goods_model.model_img
     *
     * @mbg.generated Mon Apr 30 02:41:42 CST 2018
     */
    public String getModelImg() {
        return modelImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_model.model_img
     *
     * @param modelImg the value for goods_model.model_img
     *
     * @mbg.generated Mon Apr 30 02:41:42 CST 2018
     */
    public void setModelImg(String modelImg) {
        this.modelImg = modelImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_model.goods_id
     *
     * @return the value of goods_model.goods_id
     *
     * @mbg.generated Mon Apr 30 02:41:42 CST 2018
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_model.goods_id
     *
     * @param goodsId the value for goods_model.goods_id
     *
     * @mbg.generated Mon Apr 30 02:41:42 CST 2018
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }
}