package com.icei.domain;

public class LikeGoods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like_goods.goods_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like_goods.user_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like_goods.goods_id
     *
     * @return the value of like_goods.goods_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like_goods.goods_id
     *
     * @param goodsId the value for like_goods.goods_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like_goods.user_id
     *
     * @return the value of like_goods.user_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like_goods.user_id
     *
     * @param userId the value for like_goods.user_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}