package com.icei.domain;

import java.util.*;

public class OrderAssess {
	private UserDetail userDetail;//顾客
	private BrandGoods brandGoods;//商品详情
	private List<AssessImg> ai;//商品图片集合
	
    public List<AssessImg> getAi() {
		return ai;
	}

	public void setAi(List<AssessImg> ai) {
		this.ai = ai;
	}

	public UserDetail getUserDetail() {
		return userDetail;
	}

	public void setUserDetail(UserDetail userDetail) {
		this.userDetail = userDetail;
	}

	public BrandGoods getBrandGoods() {
		return brandGoods;
	}

	public void setBrandGoods(BrandGoods brandGoods) {
		this.brandGoods = brandGoods;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_assess.assess_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer assessId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_assess.goods_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_assess.detail_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer detailId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_assess.assess_dec
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String assessDec;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_assess.user_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_assess.goods_quality
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Float goodsQuality;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_assess.server_attitude
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Float serverAttitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_assess.assess_date
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Date assessDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_assess.goods_model
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String goodsModel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_assess.like_count
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer likeCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_assess.assess_id
     *
     * @return the value of order_assess.assess_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getAssessId() {
        return assessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_assess.assess_id
     *
     * @param assessId the value for order_assess.assess_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setAssessId(Integer assessId) {
        this.assessId = assessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_assess.goods_id
     *
     * @return the value of order_assess.goods_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_assess.goods_id
     *
     * @param goodsId the value for order_assess.goods_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_assess.detail_id
     *
     * @return the value of order_assess.detail_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getDetailId() {
        return detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_assess.detail_id
     *
     * @param detailId the value for order_assess.detail_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setDetailId(Integer detailId) {
        this.detailId = detailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_assess.assess_dec
     *
     * @return the value of order_assess.assess_dec
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getAssessDec() {
        return assessDec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_assess.assess_dec
     *
     * @param assessDec the value for order_assess.assess_dec
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setAssessDec(String assessDec) {
        this.assessDec = assessDec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_assess.user_id
     *
     * @return the value of order_assess.user_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_assess.user_id
     *
     * @param userId the value for order_assess.user_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_assess.goods_quality
     *
     * @return the value of order_assess.goods_quality
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Float getGoodsQuality() {
        return goodsQuality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_assess.goods_quality
     *
     * @param goodsQuality the value for order_assess.goods_quality
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setGoodsQuality(Float goodsQuality) {
        this.goodsQuality = goodsQuality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_assess.server_attitude
     *
     * @return the value of order_assess.server_attitude
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Float getServerAttitude() {
        return serverAttitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_assess.server_attitude
     *
     * @param serverAttitude the value for order_assess.server_attitude
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setServerAttitude(Float serverAttitude) {
        this.serverAttitude = serverAttitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_assess.assess_date
     *
     * @return the value of order_assess.assess_date
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Date getAssessDate() {
        return assessDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_assess.assess_date
     *
     * @param assessDate the value for order_assess.assess_date
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setAssessDate(Date assessDate) {
        this.assessDate = assessDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_assess.goods_model
     *
     * @return the value of order_assess.goods_model
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getGoodsModel() {
        return goodsModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_assess.goods_model
     *
     * @param goodsModel the value for order_assess.goods_model
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setGoodsModel(String goodsModel) {
        this.goodsModel = goodsModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_assess.like_count
     *
     * @return the value of order_assess.like_count
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_assess.like_count
     *
     * @param likeCount the value for order_assess.like_count
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }
}