package com.icei.domain;

public class Payment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.payment_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer paymentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment.payment_type
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String paymentType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.payment_id
     *
     * @return the value of payment.payment_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getPaymentId() {
        return paymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.payment_id
     *
     * @param paymentId the value for payment.payment_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setPaymentId(Integer paymentId) {
        this.paymentId = paymentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment.payment_type
     *
     * @return the value of payment.payment_type
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getPaymentType() {
        return paymentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment.payment_type
     *
     * @param paymentType the value for payment.payment_type
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setPaymentType(String paymentType) {
        this.paymentType = paymentType;
    }
}