package com.icei.domain;

import java.util.Date;

public class PowerAuthority {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_ authority.authority_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer authorityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_ authority.authority_name
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String authorityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_ authority.authority_dec
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String authorityDec;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_ authority.authority_create_time
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Date authorityCreateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_ authority.authority_update_time
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Date authorityUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_ authority.authority_id
     *
     * @return the value of power_ authority.authority_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getAuthorityId() {
        return authorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_ authority.authority_id
     *
     * @param authorityId the value for power_ authority.authority_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setAuthorityId(Integer authorityId) {
        this.authorityId = authorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_ authority.authority_name
     *
     * @return the value of power_ authority.authority_name
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getAuthorityName() {
        return authorityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_ authority.authority_name
     *
     * @param authorityName the value for power_ authority.authority_name
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setAuthorityName(String authorityName) {
        this.authorityName = authorityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_ authority.authority_dec
     *
     * @return the value of power_ authority.authority_dec
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getAuthorityDec() {
        return authorityDec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_ authority.authority_dec
     *
     * @param authorityDec the value for power_ authority.authority_dec
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setAuthorityDec(String authorityDec) {
        this.authorityDec = authorityDec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_ authority.authority_create_time
     *
     * @return the value of power_ authority.authority_create_time
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Date getAuthorityCreateTime() {
        return authorityCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_ authority.authority_create_time
     *
     * @param authorityCreateTime the value for power_ authority.authority_create_time
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setAuthorityCreateTime(Date authorityCreateTime) {
        this.authorityCreateTime = authorityCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_ authority.authority_update_time
     *
     * @return the value of power_ authority.authority_update_time
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Date getAuthorityUpdateTime() {
        return authorityUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_ authority.authority_update_time
     *
     * @param authorityUpdateTime the value for power_ authority.authority_update_time
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setAuthorityUpdateTime(Date authorityUpdateTime) {
        this.authorityUpdateTime = authorityUpdateTime;
    }
}