package com.icei.domain;

import java.util.Date;

public class PowerRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_role.role_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_role.role_name
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_role.role_describe
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String roleDescribe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_role.role_create_time
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Date roleCreateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column power_role.role_update_time
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Date roleUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_role.role_id
     *
     * @return the value of power_role.role_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_role.role_id
     *
     * @param roleId the value for power_role.role_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_role.role_name
     *
     * @return the value of power_role.role_name
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_role.role_name
     *
     * @param roleName the value for power_role.role_name
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_role.role_describe
     *
     * @return the value of power_role.role_describe
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getRoleDescribe() {
        return roleDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_role.role_describe
     *
     * @param roleDescribe the value for power_role.role_describe
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setRoleDescribe(String roleDescribe) {
        this.roleDescribe = roleDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_role.role_create_time
     *
     * @return the value of power_role.role_create_time
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Date getRoleCreateTime() {
        return roleCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_role.role_create_time
     *
     * @param roleCreateTime the value for power_role.role_create_time
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setRoleCreateTime(Date roleCreateTime) {
        this.roleCreateTime = roleCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column power_role.role_update_time
     *
     * @return the value of power_role.role_update_time
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Date getRoleUpdateTime() {
        return roleUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column power_role.role_update_time
     *
     * @param roleUpdateTime the value for power_role.role_update_time
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setRoleUpdateTime(Date roleUpdateTime) {
        this.roleUpdateTime = roleUpdateTime;
    }
}