package com.icei.domain;

public class Slideshow {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slideshow.id
     *
     * @mbg.generated Fri Apr 27 21:19:30 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slideshow.title
     *
     * @mbg.generated Fri Apr 27 21:19:30 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slideshow.content
     *
     * @mbg.generated Fri Apr 27 21:19:30 CST 2018
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slideshow.goods_img
     *
     * @mbg.generated Fri Apr 27 21:19:30 CST 2018
     */
    private String goodsImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slideshow.goods_back
     *
     * @mbg.generated Fri Apr 27 21:19:30 CST 2018
     */
    private String goodsBack;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slideshow.goods_video
     *
     * @mbg.generated Fri Apr 27 21:19:30 CST 2018
     */
    private String goodsVideo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slideshow.goods_url
     *
     * @mbg.generated Fri Apr 27 21:19:30 CST 2018
     */
    private String goodsUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slideshow.back_colour
     *
     * @mbg.generated Fri Apr 27 21:19:30 CST 2018
     */
    private String backColor;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slideshow.id
     *
     * @return the value of slideshow.id
     *
     * @mbg.generated Fri Apr 27 21:19:30 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slideshow.id
     *
     * @param id the value for slideshow.id
     *
     * @mbg.generated Fri Apr 27 21:19:30 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slideshow.title
     *
     * @return the value of slideshow.title
     *
     * @mbg.generated Fri Apr 27 21:19:30 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slideshow.title
     *
     * @param title the value for slideshow.title
     *
     * @mbg.generated Fri Apr 27 21:19:30 CST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slideshow.content
     *
     * @return the value of slideshow.content
     *
     * @mbg.generated Fri Apr 27 21:19:30 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slideshow.content
     *
     * @param content the value for slideshow.content
     *
     * @mbg.generated Fri Apr 27 21:19:30 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slideshow.goods_img
     *
     * @return the value of slideshow.goods_img
     *
     * @mbg.generated Fri Apr 27 21:19:30 CST 2018
     */
    public String getGoodsImg() {
        return goodsImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slideshow.goods_img
     *
     * @param goodsImg the value for slideshow.goods_img
     *
     * @mbg.generated Fri Apr 27 21:19:30 CST 2018
     */
    public void setGoodsImg(String goodsImg) {
        this.goodsImg = goodsImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slideshow.goods_back
     *
     * @return the value of slideshow.goods_back
     *
     * @mbg.generated Fri Apr 27 21:19:30 CST 2018
     */
    public String getGoodsBack() {
        return goodsBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slideshow.goods_back
     *
     * @param goodsBack the value for slideshow.goods_back
     *
     * @mbg.generated Fri Apr 27 21:19:30 CST 2018
     */
    public void setGoodsBack(String goodsBack) {
        this.goodsBack = goodsBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slideshow.goods_video
     *
     * @return the value of slideshow.goods_video
     *
     * @mbg.generated Fri Apr 27 21:19:30 CST 2018
     */
    public String getGoodsVideo() {
        return goodsVideo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slideshow.goods_video
     *
     * @param goodsVideo the value for slideshow.goods_video
     *
     * @mbg.generated Fri Apr 27 21:19:30 CST 2018
     */
    public void setGoodsVideo(String goodsVideo) {
        this.goodsVideo = goodsVideo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slideshow.goods_url
     *
     * @return the value of slideshow.goods_url
     *
     * @mbg.generated Fri Apr 27 21:19:30 CST 2018
     */
    public String getGoodsUrl() {
        return goodsUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slideshow.goods_url
     *
     * @param goodsUrl the value for slideshow.goods_url
     *
     * @mbg.generated Fri Apr 27 21:19:30 CST 2018
     */
    public void setGoodsUrl(String goodsUrl) {
        this.goodsUrl = goodsUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slideshow.back_colour
     *
     * @return the value of slideshow.back_colour
     *
     * @mbg.generated Fri Apr 27 21:19:30 CST 2018
     */
    public String getBackColor() {
        return backColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slideshow.back_colour
     *
     * @param backColour the value for slideshow.back_colour
     *
     * @mbg.generated Fri Apr 27 21:19:30 CST 2018
     */
    public void setBackColor(String backColor) {
        this.backColor = backColor;
    }
}