package com.icei.domain;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

public class Template {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.discount_template_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer discountTemplateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.discounts_start_time
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
	@DateTimeFormat(pattern="yyyy-MM-dd")
	//转换时间类型显示问题@JsonFormat(pattern="yyyy-MM-dd HH:mm")
    private Date discountsStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.discounts_end_time
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
	@DateTimeFormat(pattern="yyyy-MM-dd")
	//转换时间类型显示问题@JsonFormat(pattern="yyyy-MM-dd HH:mm")
    private Date discountsEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.discounts_scope
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer discountsScope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.brand_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer brandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.big_money
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer bigMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.small_money
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer smallMoney;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.discount_template_id
     *
     * @return the value of template.discount_template_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getDiscountTemplateId() {
        return discountTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.discount_template_id
     *
     * @param discountTemplateId the value for template.discount_template_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setDiscountTemplateId(Integer discountTemplateId) {
        this.discountTemplateId = discountTemplateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.discounts_start_time
     *
     * @return the value of template.discounts_start_time
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Date getDiscountsStartTime() {
        return discountsStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.discounts_start_time
     *
     * @param discountsStartTime the value for template.discounts_start_time
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setDiscountsStartTime(Date discountsStartTime) {
        this.discountsStartTime = discountsStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.discounts_end_time
     *
     * @return the value of template.discounts_end_time
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Date getDiscountsEndTime() {
        return discountsEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.discounts_end_time
     *
     * @param discountsEndTime the value for template.discounts_end_time
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setDiscountsEndTime(Date discountsEndTime) {
        this.discountsEndTime = discountsEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.discounts_scope
     *
     * @return the value of template.discounts_scope
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getDiscountsScope() {
        return discountsScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.discounts_scope
     *
     * @param discountsScope the value for template.discounts_scope
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setDiscountsScope(Integer discountsScope) {
        this.discountsScope = discountsScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.brand_id
     *
     * @return the value of template.brand_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.brand_id
     *
     * @param brandId the value for template.brand_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.big_money
     *
     * @return the value of template.big_money
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getBigMoney() {
        return bigMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.big_money
     *
     * @param bigMoney the value for template.big_money
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setBigMoney(Integer bigMoney) {
        this.bigMoney = bigMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.small_money
     *
     * @return the value of template.small_money
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getSmallMoney() {
        return smallMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.small_money
     *
     * @param smallMoney the value for template.small_money
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setSmallMoney(Integer smallMoney) {
        this.smallMoney = smallMoney;
    }
}