package com.icei.domain;

public class UserAddress {
    @Override
    public String toString() {
        return "UserAddress{" +
                "addressId=" + addressId +
                ", userId=" + userId +
                ", name='" + name + '\'' +
                ", phone='" + phone + '\'' +
                ", region='" + region + '\'' +
                ", street='" + street + '\'' +
                ", postcode='" + postcode + '\'' +
                ", tally='" + tally + '\'' +
                '}';
    }
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.address_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer addressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.user_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.name
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.phone
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.region
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String region;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.street
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String street;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.postcode
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String postcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_address.tally
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String tally;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.address_id
     *
     * @return the value of user_address.address_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.address_id
     *
     * @param addressId the value for user_address.address_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.user_id
     *
     * @return the value of user_address.user_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.user_id
     *
     * @param userId the value for user_address.user_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.name
     *
     * @return the value of user_address.name
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.name
     *
     * @param name the value for user_address.name
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.phone
     *
     * @return the value of user_address.phone
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.phone
     *
     * @param phone the value for user_address.phone
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.region
     *
     * @return the value of user_address.region
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.region
     *
     * @param region the value for user_address.region
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setRegion(String region) {
        this.region = region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.street
     *
     * @return the value of user_address.street
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getStreet() {
        return street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.street
     *
     * @param street the value for user_address.street
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setStreet(String street) {
        this.street = street;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.postcode
     *
     * @return the value of user_address.postcode
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.postcode
     *
     * @param postcode the value for user_address.postcode
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_address.tally
     *
     * @return the value of user_address.tally
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getTally() {
        return tally;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_address.tally
     *
     * @param tally the value for user_address.tally
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setTally(String tally) {
        this.tally = tally;
    }
}