package com.icei.domain;

import java.util.Date;

public class UserDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_detail.user_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_detail.user_name
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_detail.user_code
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String userCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_detail.user_gender
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer userGender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_detail.phone_num
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String phoneNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_detail.user_status
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer userStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_detail.user_integral
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Float userIntegral;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_detail.img_path
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private String imgPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_detail.creation_date
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Date creationDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_detail.user_id
     *
     * @return the value of user_detail.user_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_detail.user_id
     *
     * @param userId the value for user_detail.user_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_detail.user_name
     *
     * @return the value of user_detail.user_name
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_detail.user_name
     *
     * @param userName the value for user_detail.user_name
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_detail.user_code
     *
     * @return the value of user_detail.user_code
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_detail.user_code
     *
     * @param userCode the value for user_detail.user_code
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_detail.user_gender
     *
     * @return the value of user_detail.user_gender
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getUserGender() {
        return userGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_detail.user_gender
     *
     * @param userGender the value for user_detail.user_gender
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setUserGender(Integer userGender) {
        this.userGender = userGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_detail.phone_num
     *
     * @return the value of user_detail.phone_num
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getPhoneNum() {
        return phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_detail.phone_num
     *
     * @param phoneNum the value for user_detail.phone_num
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setPhoneNum(String phoneNum) {
        this.phoneNum = phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_detail.user_status
     *
     * @return the value of user_detail.user_status
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_detail.user_status
     *
     * @param userStatus the value for user_detail.user_status
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setUserStatus(Integer userStatus) {
        this.userStatus = userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_detail.user_integral
     *
     * @return the value of user_detail.user_integral
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Float getUserIntegral() {
        return userIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_detail.user_integral
     *
     * @param userIntegral the value for user_detail.user_integral
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setUserIntegral(Float userIntegral) {
        this.userIntegral = userIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_detail.img_path
     *
     * @return the value of user_detail.img_path
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public String getImgPath() {
        return imgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_detail.img_path
     *
     * @param imgPath the value for user_detail.img_path
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_detail.creation_date
     *
     * @return the value of user_detail.creation_date
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Date getCreationDate() {
        return creationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_detail.creation_date
     *
     * @param creationDate the value for user_detail.creation_date
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
}