package com.icei.domain;

public class UserRelation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_relation.user_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_relation.new_user_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    private Integer newUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_relation.user_id
     *
     * @return the value of user_relation.user_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_relation.user_id
     *
     * @param userId the value for user_relation.user_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_relation.new_user_id
     *
     * @return the value of user_relation.new_user_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public Integer getNewUserId() {
        return newUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_relation.new_user_id
     *
     * @param newUserId the value for user_relation.new_user_id
     *
     * @mbg.generated Thu Apr 19 10:27:54 CST 2018
     */
    public void setNewUserId(Integer newUserId) {
        this.newUserId = newUserId;
    }
}